pipeline {
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./SOFE3980U-ProjectDeliverable1/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn package -DskipTests -f ./SOFE3980U-ProjectDeliverable1/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        sh 'echo "end"'
      }
    }
  }
}
